# Main Text
author: Archeostickers
name: Archeostickers

title: 'Archeostickers'
subtitle: 'Cose antiche sfrontate'
payoff: 'Cose antiche sfrontate'
description: "Cose del passato dicono parole sul presente. Lì dove c'erano epigrammi ci stanno i meme."
locale: it_IT

# Url
baseurl: "" # the subpath of your site, e.g. /blog
url: https://archeostickers.com

# Contact
twitter: archeostickers
github:  archeostickers
facebook: archeostickers
email: contact@osd.tools
github_username: archeostickers
facebook_username: archeostickers
twitter_username: archeostickers

# SEO
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/img/osd-opg-facebook.png"

# Favicon
touch_icon: "assets/img/logos/apple-touch-icon-144-precomposed.png"
favicon: "/assets/img/favicon/favicon.ico"

# Build settings
markdown: kramdown
highlighter: rouge

#paginate
paginate: 5

sass:
  sass_dir: _sass
  style: compression

collections:
  activities:
    output: true
  services:
    output: true



plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-coffeescript

exclude:
  - Gemfile
  - Gemfile.lock
