# Main Text
author: Archeostickers
name: Archeostickers

title: 'Archeostickers'
subtitle: 'Sfacciati Classici'
payoff: 'Sfacciati Classici'
timecopy: "2015-2019"

description: "Archeostickers, sticker sfacciate da reperti d'arte."
locale: it_IT

# Url
baseurl: "" # the subpath of your site, e.g. /blog
url: https://archeostickers.com

# Contact
twitter:
  username: archeostickers
  card: summary_large_image
github:  archeostickers
facebook: archeostickers
instagram: archeostickers
email: contact@osd.tools
github_username: archeostickers
facebook_username: archeostickers
twitter_username: archeostickers

# SEO
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/img/archeo-opg-facebook.png"

# Favicon
touch_icon: "assets/img/apple-touch-icon-144-precomposed.png"
favicon: "/assets/img/favicon/favicon.ico"

# Build settings
markdown: kramdown
highlighter: rouge

#paginate
# paginate: 10

sass:
  sass_dir: _sass
  style: compression

collections:
  activities:
    output: true
  services:
    output: true



plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-coffeescript

exclude:
  - Gemfile
  - Gemfile.lock
